### ISSUE TITLE
Add WAFS to GFSv17 workflow

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/EMC_gfs_wafs#15]
Add WAFS to GFSv17 global ecflow.
1. Merge wafs update for GFSv16 to wafs 'develop' branch
2. Cleaned up WAFS legacy files that are no longer needed
- Removed outdated fix/wafs parm/wafs files
- Removed 1.25 hazard grib2 source code sorc/wafs_awc_wafavn.fd sorc/wafs_blending.fd sorc/wafs_setmissing.fd, updated sorc/build_wafs.sh sorc/CMakeLists.txt
- Removed 1.25 hazard grib2 parts from parm/script/ush files
- Removed 1.25 blend parm/script/ush file
- Removed ICAO2023=no related lines, updated related scripts/ush
- Removed GRIB octant related ush file and updated the script
- Renamed some fix files for better organizing the fix filenames
3. EIB will update cmake in WAFS develop
4. Add jobs, scripts and ush to GFS v17 workflow repository
5. EIB will update one WAFS J-job as a demonstration
6. Update other WAFS J-jobs accordingly with EIB’s help

Update reminders:
1. Blend US own product if UK unblended data misses the waiting time window
2. UPP remove output on ICAO standard atmospheric levels
3. Switch VVEL to dzdt
4. May be merged with issue #14 
5. Update forecat hour from 2 digits to 3 digits, as addressed in issue #11

**Comment by YaliMao-NOAA** [comment]
@HuiyaChuang-NOAA 
We are exploring to apply 'near neighbor' interpolation to CB, instead of 'linear' interpolation.

**Comment by YaliMao-NOAA** [comment]
1. Merge wafs update for GFSv16  to wafs 'develop' branch
https://github.com/NOAA-EMC/EMC_gfs_wafs/commit/717233ba7c667df2da6930c466bfc6993253a522

**Comment by YaliMao-NOAA** [comment]
As to step 2, PR #19 is merged.
2. Cleaned up WAFS legacy files that are no longer needed
- Removed outdated fix/wafs parm/wafs files
- Removed 1.25 hazard grib2 source code sorc/wafs_awc_wafavn.fd sorc/wafs_blending.fd sorc/wafs_setmissing.fd, updated sorc/build_wafs.sh sorc/CMakeLists.txt
- Removed 1.25 hazard grib2 parts from parm/script/ush files
- Removed 1.25 blend parm/script/ush file
- Removed ICAO2023=no related lines, updated related scripts/ush
- Removed GRIB octant related ush file and updated the script
- Renamed some fix files for better organizing the fix filenames
Updated drivers for GFSv16.3 after this clean-up

As a based line, I ran a set of wafs data which were bit-wise identical to the operational products except one GCIP file which depends DCOM METAR observation accumulative data.

@aerorahul WAFS is ready for you to update CMake related parts. Thank you for your help.

**Comment by YaliMao-NOAA** [comment]
3. EIB will update cmake in WAFS develop
It's done in PR #20

**Comment by YaliMao-NOAA** [comment]
@aerorahul In global workflow,  should I delete the ignored llines related to WAFS in .gitignore?

The lines should be related to jobs/scripts/ush, not parm

**Comment by YaliMao-NOAA** [comment]
4. Add jobs, scripts and ush to GFS v17 workflow repository
@aerorahul 
I simply copied WAFS jobs/scripts/ush to GFS v17 workflow, and made a PR [#2412](https://github.com/NOAA-EMC/global-workflow/pull/2412). Please let me know if I am not doing the right thing.
For the next step, may you please help to get jobs/JGFS_ATMOS_WAFS_GRIB2 to work?

**Comment by aerorahul** [comment]
This should be closed as WAFS will not be going to GFSv17
