### ISSUE TITLE
Port to S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_gfs_wafs#3]
In porting the global workflow to S4, the WAFS component also needs to be ported.  Though there are no plans to run WAFS on S4, it still needs to be buildable.

**Comment by aerorahul** [comment]
It is no longer necessary to port WAFS to any platform for the purposes of global-workflow.
WAFS will no longer be built in the global-workflow package.
Closing as OBE.
