### ISSUE TITLE
Build WAFS `develop` on WCOSS2.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/EMC_gfs_wafs#9]
In preparation for GFSv17, WAFS `develop` branch should be able to be built on WCOSS2.
In addition, `w3nco` library has been deprecated and its use should be replaced w/ `w3emc`.

**Comment by YaliMao-NOAA** [comment]
Hi Rahul,
I usually modify and run the drivers under driver/. But the drivers of develop branch are all outdated. The new ones working on WCOSS2 are under branch implement2023: https://github.com/NOAA-EMC/EMC_gfs_wafs/tree/implement2023

**Comment by aerorahul** [comment]
@YaliMao-NOAA 
There is no `cmake` build in this branch.  Also this branch is significantly diverged from `develop`.
The tag for GFSv17 will come from `develop`, correct?

**Comment by YaliMao-NOAA** [comment]
You are right. Develop should be the right branch, but I haven't merged the changes of GFS v16.3 WAFS implementation to it yet. I switched to work on EVS right after submitting the implementation code. The deadline of EVS is the end of this month. Can we get back in touch after that?

**Comment by aerorahul** [comment]
Yes. Absolutely.  Please take your time.
We can get back in touch early Dec.  

Meanwhile, I will open a PR when I have WAFS building on WCOSS2 with `develop` and `cmake`.

**Comment by YaliMao-NOAA** [comment]
@aerorahul  May I have a few questions?
1. The building/compiling scripts are under ush/ folder while this folder is usually dedicated for wafs workflow related scripts. Can we separate them? Then here is the second question?
2. Is sorc/ still good to save the building/compiling scripts? If not, how about build/? Or is there any convention to name the folder which saves the building/compiling scripts?
3. After running ush/build.sh, two folders are created, build/ and install/. Are these two folders supposed to be temporary?
@aerorahul @HuiyaChuang-NOAA 
4. In the big picture of GFS v17, how will WAFS fit in? Can a submodule work as we are current doing? WAFS has its own Fortran source code of GCIP and blending, and its own tailored WMO headers. Is it a wise decision to mix WAFS parm script fix folders in the big vertical structure of GFS as mentioned in the meeting of GFS v17 / GEFS v13 Infrastructure planning yesterday?

**Comment by aerorahul** [comment]
@YaliMao-NOAA 
Let me attempt to address your questions.
1. The `build.sh` is a shell script for the project.  We have been placing these files in `ush/` in all projects.  You can see it in the GSI, GSI-utils, GFS-utils, obsproc, etc.  We will be making similar changes in the other components across EMC projects that are not consistent with this approach.
2. See 1.  `build` can be discarded as soon as the build is complete and executables created.
3. `build` and `install` are the build and installation directories for the project.  This is a `cmake` property of out-of-source builds.  These directories are not added to the repository and these directories need not be in the repo directory either.
4. This probably needs more explanation so I can understand the question correctly. Can we discuss this point offline?

**Comment by YaliMao-NOAA** [comment]
@aerorahul 
1. Are you saying ush/ will be the standard way where to save build.sh? Will it conflict NCO code management? If it's okay, I will follow it.
As to 4. Sure, let's discuss it off and I've scheduled a meeting next Monday.

**Comment by aerorahul** [comment]
> @aerorahul
> 
> 1. Are you saying ush/ will be the standard way where to save build.sh? Will it conflict NCO code management? If it's okay, I will follow it.
>    As to 4. Sure, let's discuss it off and I've scheduled a meeting next Monday.

1. is already in place for obs. proc.
2. Thank you for scheduling meet.

**Comment by aerorahul** [comment]
OBE.
